image: python:3.11

cache:
  paths:
    - ~/.cache/pip
    - ~/.platformio/.cache

stages:
 - build_en
 - build_de

default:
  tags:
    - docker

before_script:
  - "pip install --upgrade pip"
  - "pip install -U platformio"

build_en:
  stage: build_en
  script:
    - "pio run -e r4wifi_en"
    - cp .pio/build/r4wifi_en/firmware.bin .pio/build/r4wifi_en/firmware_en.bin
  artifacts:
    paths:
      - .pio/build/r4wifi_en/firmware_en.bin
  environment: firmware_en
  rules:
    - if: $CI_COMMIT_BRANCH == "r4wifiv2"

build_de:
  stage: build_de
  script: 
    - "pio run -e r4wifi_de"
    - cp .pio/build/r4wifi_de/firmware.bin .pio/build/r4wifi_de/firmware_de.bin
  artifacts:
    paths:
      - .pio/build/r4wifi_de/firmware_de.bin
  environment: firmware_de
  rules:
    - if: $CI_COMMIT_BRANCH == "r4wifiv2"
