; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
	
[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
	microbahner/MobaTools@^2.6.1
	paulstoffregen/Encoder@^1.4.4
	fmalpartida/LiquidCrystal@^1.5.0
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	Wire
monitor_speed = 115200
upload_port = /dev/cu.wchusbserial1410
; uncomment next lines for versioning and/or debugging
build_flags =
  -D VERSION=0.0.4-prod
	;-D DEBUG
	; detailed stepper and encoder positions, DEBUG has to be defined, too
	;-D DEBUG_POSITION
