; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
	microbahner/MobaTools@^2.6.1
	paulstoffregen/Encoder@^1.4.4
	fmalpartida/LiquidCrystal@^1.5.0
	Wire
	end2endzone/AnyRtttl@^2.3
	siara-cc/Unishox Progmem Decompressor@^1.0
	thomasfredericks/Bounce2@^2.72
extra_scripts = post:autoversionincrement.py
monitor_speed = 115200
check_tool = cppcheck
check_flags = 
	cppcheck: --enable=performance --enable=warning --inline-suppr src lib include
