baseURL = 'https://pages.open-mind.space/knittingmotor'
languageCode = 'en-us'
title = 'Open Knitting Motor Project'
theme = ['techdoc', 'hugo-shortcode-gallery']

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[params]
# Documentation Menu section
# Menu style settings
menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar
#menu_style = ""
custom_background_color = "#636361"
#custom_font_color = "black"
custom_font_color = "#f7e8d0"

# Global menu section
# See https://gohugo.io/content-management/menus/

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
        identifier = 'home'
        pre = "<i class='fa fa-ruler-combined'></i>&nbsp;"

    [[menu.main]]
        name = "Source files"
        url = "https://gitlab.open-mind.space/pages/knittingmotor"
        weight = 40
        identifier = 'download_sc'

    [[menu.main]]
        name = "Firmware download"
        url = "https://gitlab.open-mind.space/pages/knittingmotor/-/releases/permalink/latest"
        weight = 50
        identifier = 'download_fw'

    [[menu.main]]
        name = "Impressum/Imprint"
        url = "/impressum"
        weight = 1000
        identifier = 'impressum'


# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 6
        ordered = false

